# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Makers Making Change
tagline:             'blog'
description:         'Latest blog updates about <a href="http://www.makersmakingchange.com/" target="_blank">Makers Making Change</a> projects.'
url:                 http://www.makersmakingchange.com/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              
  url:               http://www.makersmakingchange.com/
  email:             info@makersmakingchange.com

# Custom vars
version:             1.0.0

theme: jekyll-theme-minimal
